### ISSUE TITLE
feat: convert basic info in Candidate App to the Question-Answer-model

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#562]
### Subtasks

- [ ] Convert `/candidate/(protected)/profile` to use the `Question`-`Answer`-paradigm
- [ ] Clean up Strapi content model: remove unnecessary props from `Candidate` and the whole `Candidate Attributes` type
- [ ] Update mock data generation

This will also fix current issues with Candidate preview.
