### ISSUE TITLE
feat: DataWriter API between the front and backend for editing data

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#575]
See [a list of possible API calls](https://docs.google.com/spreadsheets/d/1Q6c_bDJhBVJ8TWe38nr5wWZ0d_Mpor_DcyTL2Ay90VU/edit?usp=sharing).

Consider also:
- Should there be a separate `Authenticator` interface or just let `DataWriter` handle that end-to-end?
- What are the functions that we should expect all implementations to provide?
  - Can we expect password resetting to always happen via an email link?
  - What about bank authentication? This doesn't require a registration code, and the candidate might have to enter their party by themselves.
- Should the `DataWriter` also come with a `capabilities` property that could be used by the frontend to know which functions are available?

### Subtasks

- [ ] Make the list of API calls as generic and succint as possible.
- [ ] Move all API call implementations in the Candidate App from pages and components into the generic `dataWriter` module, see for example the `<QuestionPage>` template.
- [ ] Harmonize API calls between the Voter and Candidate Apps.
- [ ] Check TODOs in source code marked with `[DataWriter]`
